export const NEXT_FLOW = 'NEXT_FLOW'
export const BACK_FLOW = 'BACK_FLOW'
export const BACK_WAIT_PAGE = 'BACK_LAST_FLOW'
export const SAVE_INPUT = 'SAVE_INPUT'
export const OPEN_KEYBOARD = 'OPEN_KEYBOARD'
export const CLOSE_KEYBOARD = 'CLOSE_KEYBOARD'
export const CHANGE_INPUT_NAME = 'CHANGE_INPUT_NAME'
export const REMOVE_GUEST = 'REMOVE_GUEST'
export const ADD_GUEST = 'ADD_GUEST'
export const VALIDATE_FIELDS = 'VALIDATE_FIELDS'
export const BOOKING_RETURNED = 'BOOKING_RETURNED'







