export const data = {
  step: 0,
  totalSteps: 7,
  visitingPet: false,
  petPolicyChecked: false,
  policyChecked: false,
  additionalGuests: [{id: 0, 'name0': ''}],
  count: 1,
  inputsSearch: {},
  inputsCustomerInfo: {},
  fieldsCustomerInfo: [
    { "phone": { value: '', error: false } },
    { "zipcode": { value: '', error: false } },
    { "country": { value: '', error: false } },
    { "email": { value: '', error: false } },
    { "address": { value: '', error: false } },
    { "city": { value: '', error: false } },
    { "state": { value: '', error: false } },
  ],
  customerInfoValid: false,
  inputs: {},
  keyboardVisibility: 'none',
  opacity: 0,
  checkinDate: undefined,
  checkoutDate: undefined,
  room: '',
  bookingId: '',
  lastStep: 0
}
